# Generated by Django 4.1.7 on 2023-04-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_goalcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='deadline_date',
            new_name='due_date',
        ),
    ]
