# Generated by Django 4.1.7 on 2023-04-19 16:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0004_board_goalcategory_board_boardparticiant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoardParticiant',
            new_name='BoardParticipant',
        ),
    ]
